#!/bin/bash

jq -r '
  . as $root |
  "\(.name) is of type \(.types[0].type.name), weighs \(.weight/10)kg, and is \(.height/10)m tall."
' data.json | \
sed 's/\b\(.\)/\u\1/' | \
sed 's/type \([a-z]\)/type \u\1/'#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)
formatted_weight=$(awk "BEGIN {printf \"%.1f\", $weight/10}")
formatted_height=$(awk "BEGIN {printf \"%.1f\", $height/10}")

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."